=begin comment

Elastic Email REST API

This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    To start using this API, you will need your Access Token (available <a href=\"https://elasticemail.com/account#/settings/new/manage-api\">here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    This is the documentation for REST API. If you’d like to read our legacy documentation regarding Web API v2 click <a href=\"https://api.elasticemail.com/public/help\">here</a>.

The version of the OpenAPI document: 4.0.0
Contact: support@elasticemail.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
package ElasticEmail::Object::EmailStatus;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;

use ElasticEmail::Object::LogJobStatus;

use base ("Class::Accessor", "Class::Data::Inheritable");

#
#Status information of the specified email
#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech). Do not edit the class manually.
# REF: https://openapi-generator.tech
#

=begin comment

Elastic Email REST API

This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    To start using this API, you will need your Access Token (available <a href=\"https://elasticemail.com/account#/settings/new/manage-api\">here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    This is the documentation for REST API. If you’d like to read our legacy documentation regarding Web API v2 click <a href=\"https://api.elasticemail.com/public/help\">here</a>.

The version of the OpenAPI document: 4.0.0
Contact: support@elasticemail.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
__PACKAGE__->mk_classdata('attribute_map' => {});
__PACKAGE__->mk_classdata('openapi_types' => {});
__PACKAGE__->mk_classdata('method_documentation' => {}); 
__PACKAGE__->mk_classdata('class_documentation' => {});

# new plain object
sub new { 
    my ($class, %args) = @_; 

    my $self = bless {}, $class;

    $self->init(%args);
    
    return $self;
}

# initialize the object
sub init
{
    my ($self, %args) = @_;

    foreach my $attribute (keys %{$self->attribute_map}) {
        my $args_key = $self->attribute_map->{$attribute};
        $self->$attribute( $args{ $args_key } );
    }
}

# return perl hash
sub to_hash {
    my $self = shift;
    my $_hash = decode_json(JSON->new->convert_blessed->encode($self));

    return $_hash;
}

# used by JSON for serialization
sub TO_JSON { 
    my $self = shift;
    my $_data = {};
    foreach my $_key (keys %{$self->attribute_map}) {
        if (defined $self->{$_key}) {
            $_data->{$self->attribute_map->{$_key}} = $self->{$_key};
        }
    }

    return $_data;
}

# from Perl hashref
sub from_hash {
    my ($self, $hash) = @_;

    # loop through attributes and use openapi_types to deserialize the data
    while ( my ($_key, $_type) = each %{$self->openapi_types} ) {
        my $_json_attribute = $self->attribute_map->{$_key}; 
        if ($_type =~ /^array\[(.+)\]$/i) { # array
            my $_subclass = $1;
            my @_array = ();
            foreach my $_element (@{$hash->{$_json_attribute}}) {
                push @_array, $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \@_array;
        } elsif ($_type =~ /^hash\[string,(.+)\]$/i) { # hash
            my $_subclass = $1;
            my %_hash = ();
            while (my($_key, $_element) = each %{$hash->{$_json_attribute}}) {
                $_hash{$_key} = $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \%_hash;
        } elsif (exists $hash->{$_json_attribute}) { #hash(model), primitive, datetime
            $self->{$_key} = $self->_deserialize($_type, $hash->{$_json_attribute});
        } else {
            $log->debugf("Warning: %s (%s) does not exist in input hash\n", $_key, $_json_attribute);
        }
    }
  
    return $self;
}

# deserialize non-array data
sub _deserialize {
    my ($self, $type, $data) = @_;
    $log->debugf("deserializing %s with %s",Dumper($data), $type);

    if ($type eq 'DateTime') {
        return DateTime->from_epoch(epoch => str2time($data));
    } elsif ( grep( /^$type$/, ('int', 'double', 'string', 'boolean'))) {
        return $data;
    } else { # hash(model)
        my $_instance = eval "ElasticEmail::Object::$type->new()";
        return $_instance->from_hash($data);
    }
}



__PACKAGE__->class_documentation({description => 'Status information of the specified email',
                                  class => 'EmailStatus',
                                  required => [], # TODO
}                                 );

__PACKAGE__->method_documentation({
    'from' => {
        datatype => 'string',
        base_name => 'From',
        description => 'Email address this email was sent from.',
        format => '',
        read_only => '',
            },
    'to' => {
        datatype => 'string',
        base_name => 'To',
        description => 'Email address this email was sent to.',
        format => '',
        read_only => '',
            },
    'date' => {
        datatype => 'DateTime',
        base_name => 'Date',
        description => 'Date the email was submitted.',
        format => '',
        read_only => '',
            },
    'status' => {
        datatype => 'LogJobStatus',
        base_name => 'Status',
        description => 'Value of email&#39;s status',
        format => '',
        read_only => '',
            },
    'status_name' => {
        datatype => 'string',
        base_name => 'StatusName',
        description => 'Name of email&#39;s status',
        format => '',
        read_only => '',
            },
    'status_change_date' => {
        datatype => 'DateTime',
        base_name => 'StatusChangeDate',
        description => 'Date of last status change.',
        format => '',
        read_only => '',
            },
    'date_sent' => {
        datatype => 'DateTime',
        base_name => 'DateSent',
        description => 'Date when the email was sent',
        format => '',
        read_only => '',
            },
    'date_opened' => {
        datatype => 'DateTime',
        base_name => 'DateOpened',
        description => 'Date when the email changed the status to &#39;opened&#39;',
        format => '',
        read_only => '',
            },
    'date_clicked' => {
        datatype => 'DateTime',
        base_name => 'DateClicked',
        description => 'Date when the email changed the status to &#39;clicked&#39;',
        format => '',
        read_only => '',
            },
    'error_message' => {
        datatype => 'string',
        base_name => 'ErrorMessage',
        description => 'Detailed error or bounced message.',
        format => '',
        read_only => '',
            },
    'transaction_id' => {
        datatype => 'string',
        base_name => 'TransactionID',
        description => 'ID number of transaction',
        format => '',
        read_only => '',
            },
    'envelope_from' => {
        datatype => 'string',
        base_name => 'EnvelopeFrom',
        description => 'Envelope from address',
        format => '',
        read_only => '',
            },
});

__PACKAGE__->openapi_types( {
    'from' => 'string',
    'to' => 'string',
    'date' => 'DateTime',
    'status' => 'LogJobStatus',
    'status_name' => 'string',
    'status_change_date' => 'DateTime',
    'date_sent' => 'DateTime',
    'date_opened' => 'DateTime',
    'date_clicked' => 'DateTime',
    'error_message' => 'string',
    'transaction_id' => 'string',
    'envelope_from' => 'string'
} );

__PACKAGE__->attribute_map( {
    'from' => 'From',
    'to' => 'To',
    'date' => 'Date',
    'status' => 'Status',
    'status_name' => 'StatusName',
    'status_change_date' => 'StatusChangeDate',
    'date_sent' => 'DateSent',
    'date_opened' => 'DateOpened',
    'date_clicked' => 'DateClicked',
    'error_message' => 'ErrorMessage',
    'transaction_id' => 'TransactionID',
    'envelope_from' => 'EnvelopeFrom'
} );

__PACKAGE__->mk_accessors(keys %{__PACKAGE__->attribute_map});


1;
