=begin comment

Elastic Email REST API

This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    The API has a limit of 20 concurrent connections and a hard timeout of 600 seconds per request.    To start using this API, you will need your Access Token (available <a target='_blank' href='https://app.elasticemail.com/marketing/settings/new/manage-api'>here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    Downloadable library clients can be found in our Github repository <a target='_blank' href='https://github.com/ElasticEmail?tab=repositories&q=%22rest+api%22+in%3Areadme'>here</a>

The version of the OpenAPI document: 4.0.0
Contact: support@elasticemail.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
package ElasticEmail::Object::Webhook;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;


use base ("Class::Accessor", "Class::Data::Inheritable");

#
#Notification webhook setting
#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech). Do not edit the class manually.
# REF: https://openapi-generator.tech
#

=begin comment

Elastic Email REST API

This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    The API has a limit of 20 concurrent connections and a hard timeout of 600 seconds per request.    To start using this API, you will need your Access Token (available <a target='_blank' href='https://app.elasticemail.com/marketing/settings/new/manage-api'>here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    Downloadable library clients can be found in our Github repository <a target='_blank' href='https://github.com/ElasticEmail?tab=repositories&q=%22rest+api%22+in%3Areadme'>here</a>

The version of the OpenAPI document: 4.0.0
Contact: support@elasticemail.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
__PACKAGE__->mk_classdata('attribute_map' => {});
__PACKAGE__->mk_classdata('openapi_types' => {});
__PACKAGE__->mk_classdata('method_documentation' => {});
__PACKAGE__->mk_classdata('class_documentation' => {});

# new plain object
sub new {
    my ($class, %args) = @_;

    my $self = bless {}, $class;

    $self->init(%args);

    return $self;
}

# initialize the object
sub init
{
    my ($self, %args) = @_;

    foreach my $attribute (keys %{$self->attribute_map}) {
        my $args_key = $self->attribute_map->{$attribute};
        $self->$attribute( $args{ $args_key } );
    }
}

# return perl hash
sub to_hash {
    my $self = shift;
    my $_hash = decode_json(JSON->new->convert_blessed->encode($self));

    return $_hash;
}

# used by JSON for serialization
sub TO_JSON {
    my $self = shift;
    my $_data = {};
    foreach my $_key (keys %{$self->attribute_map}) {
        if (defined $self->{$_key}) {
            my $_json_attribute = $self->attribute_map->{$_key};
            my $_type = $self->openapi_types->{$_key};
            my $_value = $self->{$_key};
            if ($_type =~ /^array\[(.+)\]$/i) { # array
                my $_subclass = $1;
                $_data->{$_json_attribute} =  [ map { $self->_to_json_primitives($_subclass, $_) } @$_value ];
            } elsif ($_type =~ /^hash\[string,(.+)\]$/i) { # hash
                my $_subclass = $1;
                my %_hash = ();
                while (my($_key, $_element) = each %{$_value}) {
                    $_hash{$_key} = $self->_to_json_primitives($_subclass, $_element);
                }
                $_data->{$_json_attribute} = \%_hash;
            } elsif ( grep( /^$_type$/, ('int', 'double', 'string', 'boolean', 'DATE', 'DATE_TIME'))) {
                $_data->{$_json_attribute} = $self->_to_json_primitives($_type, $_value);
            } else {
                $_data->{$_json_attribute} = $_value;
            }
        }
    }

    return $_data;
}

# to_json non-array data
sub _to_json_primitives {
    my ($self, $type, $data) = @_;
    if ( grep( /^$type$/, ('int', 'double'))) {
        # https://metacpan.org/pod/JSON#simple-scalars
        # numify it, ensuring it will be dumped as a number
        return undef unless defined $data;
        return $data + 0;
    } elsif ($type eq 'string') {
        # https://metacpan.org/pod/JSON#simple-scalars
        # stringified
        return undef unless defined $data;
        return $data . q();
    } elsif ($type eq 'boolean') {
        # https://metacpan.org/pod/JSON#JSON::true,-JSON::false,-JSON::null
        return $data ? \1 : \0;
    } elsif ($type eq 'DATE') {
        return undef unless defined $data;
        if (ref($data) eq 'DateTime') {
            # https://metacpan.org/pod/DateTime#$dt-%3Eymd($optional_separator),-$dt-%3Emdy(...),-$dt-%3Edmy(...)
            return $data->ymd;
        }
        return $data .q();
    } elsif ($type eq 'DATE_TIME') {
        return undef unless defined $data;
        # the date-time notation as defined by RFC 3339, section 5.6, for example, 2017-07-21T17:32:28Z
        if (ref($data) eq 'DateTime') {
            # https://metacpan.org/pod/DateTime#$dt-%3Erfc3339
            return $data->rfc3339;
        }
        return $data .q();
    } else { # hash (model),  In this case, the TO_JSON of the $data object is executed
        return $data;
    }
}

# from Perl hashref
sub from_hash {
    my ($self, $hash) = @_;

    # loop through attributes and use openapi_types to deserialize the data
    while ( my ($_key, $_type) = each %{$self->openapi_types} ) {
        my $_json_attribute = $self->attribute_map->{$_key};
        if ($_type =~ /^array\[(.+)\]$/i) { # array
            my $_subclass = $1;
            my @_array = ();
            foreach my $_element (@{$hash->{$_json_attribute}}) {
                push @_array, $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \@_array;
        } elsif ($_type =~ /^hash\[string,(.+)\]$/i) { # hash
            my $_subclass = $1;
            my %_hash = ();
            while (my($_key, $_element) = each %{$hash->{$_json_attribute}}) {
                $_hash{$_key} = $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \%_hash;
        } elsif (exists $hash->{$_json_attribute}) { #hash(model), primitive, datetime
            $self->{$_key} = $self->_deserialize($_type, $hash->{$_json_attribute});
        } else {
            $log->debugf("Warning: %s (%s) does not exist in input hash\n", $_key, $_json_attribute);
        }
    }

    return $self;
}

# deserialize non-array data
sub _deserialize {
    my ($self, $type, $data) = @_;
    $log->debugf("deserializing %s with %s",Dumper($data), $type);

    if (grep( /^$type$/ , ('DATE_TIME', 'DATE'))) {
        return DateTime->from_epoch(epoch => str2time($data));
    } elsif ( grep( /^$type$/, ('int', 'double'))) {
        return undef unless defined $data;
        return $data + 0;
    } elsif ($type eq 'string') {
        return undef unless defined $data;
        return $data . q();
    } elsif ($type eq 'boolean') {
        return !!$data;
    } else { # hash(model)
        my $_instance = eval "ElasticEmail::Object::$type->new()";
        return $_instance->from_hash($data);
    }
}


__PACKAGE__->class_documentation({description => 'Notification webhook setting',
                                  class => 'Webhook',
                                  required => [], # TODO
}                                 );

__PACKAGE__->method_documentation({
    'webhook_id' => {
        datatype => 'string',
        base_name => 'WebhookID',
        description => 'Public webhook ID',
        format => '',
        read_only => '',
            },
    'name' => {
        datatype => 'string',
        base_name => 'Name',
        description => 'Filename',
        format => '',
        read_only => '',
            },
    'date_created' => {
        datatype => 'DATE_TIME',
        base_name => 'DateCreated',
        description => 'Creation date.',
        format => '',
        read_only => '',
            },
    'date_updated' => {
        datatype => 'DATE_TIME',
        base_name => 'DateUpdated',
        description => 'Last change date',
        format => '',
        read_only => '',
            },
    'url' => {
        datatype => 'string',
        base_name => 'URL',
        description => 'URL of notification.',
        format => '',
        read_only => '',
            },
    'notify_once_per_email' => {
        datatype => 'boolean',
        base_name => 'NotifyOncePerEmail',
        description => '',
        format => '',
        read_only => '',
            },
    'notification_for_sent' => {
        datatype => 'boolean',
        base_name => 'NotificationForSent',
        description => '',
        format => '',
        read_only => '',
            },
    'notification_for_opened' => {
        datatype => 'boolean',
        base_name => 'NotificationForOpened',
        description => '',
        format => '',
        read_only => '',
            },
    'notification_for_clicked' => {
        datatype => 'boolean',
        base_name => 'NotificationForClicked',
        description => '',
        format => '',
        read_only => '',
            },
    'notification_for_unsubscribed' => {
        datatype => 'boolean',
        base_name => 'NotificationForUnsubscribed',
        description => '',
        format => '',
        read_only => '',
            },
    'notification_for_abuse_report' => {
        datatype => 'boolean',
        base_name => 'NotificationForAbuseReport',
        description => '',
        format => '',
        read_only => '',
            },
    'notification_for_error' => {
        datatype => 'boolean',
        base_name => 'NotificationForError',
        description => '',
        format => '',
        read_only => '',
            },
    'is_enabled' => {
        datatype => 'boolean',
        base_name => 'IsEnabled',
        description => '',
        format => '',
        read_only => '',
            },
});

__PACKAGE__->openapi_types( {
    'webhook_id' => 'string',
    'name' => 'string',
    'date_created' => 'DATE_TIME',
    'date_updated' => 'DATE_TIME',
    'url' => 'string',
    'notify_once_per_email' => 'boolean',
    'notification_for_sent' => 'boolean',
    'notification_for_opened' => 'boolean',
    'notification_for_clicked' => 'boolean',
    'notification_for_unsubscribed' => 'boolean',
    'notification_for_abuse_report' => 'boolean',
    'notification_for_error' => 'boolean',
    'is_enabled' => 'boolean'
} );

__PACKAGE__->attribute_map( {
    'webhook_id' => 'WebhookID',
    'name' => 'Name',
    'date_created' => 'DateCreated',
    'date_updated' => 'DateUpdated',
    'url' => 'URL',
    'notify_once_per_email' => 'NotifyOncePerEmail',
    'notification_for_sent' => 'NotificationForSent',
    'notification_for_opened' => 'NotificationForOpened',
    'notification_for_clicked' => 'NotificationForClicked',
    'notification_for_unsubscribed' => 'NotificationForUnsubscribed',
    'notification_for_abuse_report' => 'NotificationForAbuseReport',
    'notification_for_error' => 'NotificationForError',
    'is_enabled' => 'IsEnabled'
} );

__PACKAGE__->mk_accessors(keys %{__PACKAGE__->attribute_map});


1;
