=begin comment

Elastic Email REST API

This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    The API has a limit of 20 concurrent connections and a hard timeout of 600 seconds per request.    To start using this API, you will need your Access Token (available <a target=\"_blank\" href=\"https://app.elasticemail.com/marketing/settings/new/manage-api\">here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    Downloadable library clients can be found in our Github repository <a target=\"_blank\" href=\"https://github.com/ElasticEmail?tab=repositories&q=%22rest+api%22+in%3Areadme\">here</a>

The version of the OpenAPI document: 4.0.0
Contact: support@elasticemail.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
package ElasticEmail::TemplatesApi;

require 5.6.0;
use strict;
use warnings;
use utf8;
use Exporter;
use Carp qw( croak );
use Log::Any qw($log);

use ElasticEmail::ApiClient;

use base "Class::Data::Inheritable";

__PACKAGE__->mk_classdata('method_documentation' => {});

sub new {
    my $class = shift;
    my $api_client;

    if ($_[0] && ref $_[0] && ref $_[0] eq 'ElasticEmail::ApiClient' ) {
        $api_client = $_[0];
    } else {
        $api_client = ElasticEmail::ApiClient->new(@_);
    }

    bless { api_client => $api_client }, $class;

}


#
# templates_by_name_delete
#
# Delete Template
#
# @param string $name Name of template. (required)
{
    my $params = {
    'name' => {
        data_type => 'string',
        description => 'Name of template.',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'templates_by_name_delete' } = {
        summary => 'Delete Template',
        params => $params,
        returns => undef,
        };
}
# @return void
#
sub templates_by_name_delete {
    my ($self, %args) = @_;

    # verify the required parameter 'name' is set
    unless (exists $args{'name'}) {
      croak("Missing the required parameter 'name' when calling templates_by_name_delete");
    }

    # parse inputs
    my $_resource_path = '/templates/{name}';

    my $_method = 'DELETE';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept();
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # path params
    if ( exists $args{'name'}) {
        my $_base_variable = "{" . "name" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'name'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(apikey )];

    # make the API Call
    $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    return;
}

#
# templates_by_name_get
#
# Load Template
#
# @param string $name Name of template. (required)
{
    my $params = {
    'name' => {
        data_type => 'string',
        description => 'Name of template.',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'templates_by_name_get' } = {
        summary => 'Load Template',
        params => $params,
        returns => 'Template',
        };
}
# @return Template
#
sub templates_by_name_get {
    my ($self, %args) = @_;

    # verify the required parameter 'name' is set
    unless (exists $args{'name'}) {
      croak("Missing the required parameter 'name' when calling templates_by_name_get");
    }

    # parse inputs
    my $_resource_path = '/templates/{name}';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # path params
    if ( exists $args{'name'}) {
        my $_base_variable = "{" . "name" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'name'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(apikey )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('Template', $response);
    return $_response_object;
}

#
# templates_by_name_put
#
# Update Template
#
# @param string $name Name of template. (required)
# @param TemplatePayload $template_payload  (required)
{
    my $params = {
    'name' => {
        data_type => 'string',
        description => 'Name of template.',
        required => '1',
    },
    'template_payload' => {
        data_type => 'TemplatePayload',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'templates_by_name_put' } = {
        summary => 'Update Template',
        params => $params,
        returns => 'Template',
        };
}
# @return Template
#
sub templates_by_name_put {
    my ($self, %args) = @_;

    # verify the required parameter 'name' is set
    unless (exists $args{'name'}) {
      croak("Missing the required parameter 'name' when calling templates_by_name_put");
    }

    # verify the required parameter 'template_payload' is set
    unless (exists $args{'template_payload'}) {
      croak("Missing the required parameter 'template_payload' when calling templates_by_name_put");
    }

    # parse inputs
    my $_resource_path = '/templates/{name}';

    my $_method = 'PUT';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    # path params
    if ( exists $args{'name'}) {
        my $_base_variable = "{" . "name" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'name'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # body params
    if ( exists $args{'template_payload'}) {
        $_body_data = $args{'template_payload'};
    }

    # authentication setting, if any
    my $auth_settings = [qw(apikey )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('Template', $response);
    return $_response_object;
}

#
# templates_get
#
# Load Templates
#
# @param ARRAY[TemplateScope] $scope_type Return templates with specified scope only (required)
# @param ARRAY[TemplateType] $template_types Return templates with specified type only (optional)
# @param int $limit Maximum number of returned items. (optional)
# @param int $offset How many items should be returned ahead. (optional)
{
    my $params = {
    'scope_type' => {
        data_type => 'ARRAY[TemplateScope]',
        description => 'Return templates with specified scope only',
        required => '1',
    },
    'template_types' => {
        data_type => 'ARRAY[TemplateType]',
        description => 'Return templates with specified type only',
        required => '0',
    },
    'limit' => {
        data_type => 'int',
        description => 'Maximum number of returned items.',
        required => '0',
    },
    'offset' => {
        data_type => 'int',
        description => 'How many items should be returned ahead.',
        required => '0',
    },
    };
    __PACKAGE__->method_documentation->{ 'templates_get' } = {
        summary => 'Load Templates',
        params => $params,
        returns => 'ARRAY[Template]',
        };
}
# @return ARRAY[Template]
#
sub templates_get {
    my ($self, %args) = @_;

    # verify the required parameter 'scope_type' is set
    unless (exists $args{'scope_type'}) {
      croak("Missing the required parameter 'scope_type' when calling templates_get");
    }

    # parse inputs
    my $_resource_path = '/templates';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # query params
    if ( exists $args{'scope_type'}) {
        $query_params->{'scopeType'} = $self->{api_client}->to_query_value($args{'scope_type'});
    }

    # query params
    if ( exists $args{'template_types'}) {
        $query_params->{'templateTypes'} = $self->{api_client}->to_query_value($args{'template_types'});
    }

    # query params
    if ( exists $args{'limit'}) {
        $query_params->{'limit'} = $self->{api_client}->to_query_value($args{'limit'});
    }

    # query params
    if ( exists $args{'offset'}) {
        $query_params->{'offset'} = $self->{api_client}->to_query_value($args{'offset'});
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(apikey )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('ARRAY[Template]', $response);
    return $_response_object;
}

#
# templates_post
#
# Add Template
#
# @param TemplatePayload $template_payload  (required)
{
    my $params = {
    'template_payload' => {
        data_type => 'TemplatePayload',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'templates_post' } = {
        summary => 'Add Template',
        params => $params,
        returns => 'Template',
        };
}
# @return Template
#
sub templates_post {
    my ($self, %args) = @_;

    # verify the required parameter 'template_payload' is set
    unless (exists $args{'template_payload'}) {
      croak("Missing the required parameter 'template_payload' when calling templates_post");
    }

    # parse inputs
    my $_resource_path = '/templates';

    my $_method = 'POST';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    my $_body_data;
    # body params
    if ( exists $args{'template_payload'}) {
        $_body_data = $args{'template_payload'};
    }

    # authentication setting, if any
    my $auth_settings = [qw(apikey )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('Template', $response);
    return $_response_object;
}

1;
