=begin comment

Elastic Email REST API

This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    The API has a limit of 20 concurrent connections and a hard timeout of 600 seconds per request.    To start using this API, you will need your Access Token (available <a target='_blank' href='https://app.elasticemail.com/marketing/settings/new/manage-api'>here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    Downloadable library clients can be found in our Github repository <a target='_blank' href='https://github.com/ElasticEmail?tab=repositories&q=%22rest+api%22+in%3Areadme'>here</a>

The version of the OpenAPI document: 4.0.0
Contact: support@elasticemail.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
package ElasticEmail::WebhookApi;

require 5.6.0;
use strict;
use warnings;
use utf8;
use Exporter;
use Carp qw( croak );
use Log::Any qw($log);

use ElasticEmail::ApiClient;

use base "Class::Data::Inheritable";

__PACKAGE__->mk_classdata('method_documentation' => {});

sub new {
    my $class = shift;
    my $api_client;

    if ($_[0] && ref $_[0] && ref $_[0] eq 'ElasticEmail::ApiClient' ) {
        $api_client = $_[0];
    } else {
        $api_client = ElasticEmail::ApiClient->new(@_);
    }

    bless { api_client => $api_client }, $class;

}


#
# webhook_by_publicid_delete
#
# Delete Webhook
#
# @param string $publicid  (required)
{
    my $params = {
    'publicid' => {
        data_type => 'string',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'webhook_by_publicid_delete' } = {
        summary => 'Delete Webhook',
        params => $params,
        returns => undef,
        };
}
# @return void
#
sub webhook_by_publicid_delete {
    my ($self, %args) = @_;

    # verify the required parameter 'publicid' is set
    unless (exists $args{'publicid'}) {
      croak("Missing the required parameter 'publicid' when calling webhook_by_publicid_delete");
    }

    # parse inputs
    my $_resource_path = '/webhook/{publicid}';

    my $_method = 'DELETE';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept();
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # path params
    if ( exists $args{'publicid'}) {
        my $_base_variable = "{" . "publicid" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'publicid'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(apikey )];

    # make the API Call
    $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    return;
}

#
# webhook_by_publicid_get
#
# Load Webhook
#
# @param string $publicid  (required)
{
    my $params = {
    'publicid' => {
        data_type => 'string',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'webhook_by_publicid_get' } = {
        summary => 'Load Webhook',
        params => $params,
        returns => 'Webhook',
        };
}
# @return Webhook
#
sub webhook_by_publicid_get {
    my ($self, %args) = @_;

    # verify the required parameter 'publicid' is set
    unless (exists $args{'publicid'}) {
      croak("Missing the required parameter 'publicid' when calling webhook_by_publicid_get");
    }

    # parse inputs
    my $_resource_path = '/webhook/{publicid}';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # path params
    if ( exists $args{'publicid'}) {
        my $_base_variable = "{" . "publicid" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'publicid'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(apikey )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('Webhook', $response);
    return $_response_object;
}

#
# webhook_by_publicid_put
#
# Update Webhook
#
# @param string $publicid  (required)
# @param WebhookUpdatePayload $webhook_update_payload  (required)
{
    my $params = {
    'publicid' => {
        data_type => 'string',
        description => '',
        required => '1',
    },
    'webhook_update_payload' => {
        data_type => 'WebhookUpdatePayload',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'webhook_by_publicid_put' } = {
        summary => 'Update Webhook',
        params => $params,
        returns => 'Webhook',
        };
}
# @return Webhook
#
sub webhook_by_publicid_put {
    my ($self, %args) = @_;

    # verify the required parameter 'publicid' is set
    unless (exists $args{'publicid'}) {
      croak("Missing the required parameter 'publicid' when calling webhook_by_publicid_put");
    }

    # verify the required parameter 'webhook_update_payload' is set
    unless (exists $args{'webhook_update_payload'}) {
      croak("Missing the required parameter 'webhook_update_payload' when calling webhook_by_publicid_put");
    }

    # parse inputs
    my $_resource_path = '/webhook/{publicid}';

    my $_method = 'PUT';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    # path params
    if ( exists $args{'publicid'}) {
        my $_base_variable = "{" . "publicid" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'publicid'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # body params
    if ( exists $args{'webhook_update_payload'}) {
        $_body_data = $args{'webhook_update_payload'};
    }

    # authentication setting, if any
    my $auth_settings = [qw(apikey )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('Webhook', $response);
    return $_response_object;
}

#
# webhook_get
#
# Load Webhooks
#
# @param int $limit Maximum number of returned items. (optional)
# @param int $offset How many items should be returned ahead. (optional)
{
    my $params = {
    'limit' => {
        data_type => 'int',
        description => 'Maximum number of returned items.',
        required => '0',
    },
    'offset' => {
        data_type => 'int',
        description => 'How many items should be returned ahead.',
        required => '0',
    },
    };
    __PACKAGE__->method_documentation->{ 'webhook_get' } = {
        summary => 'Load Webhooks',
        params => $params,
        returns => 'ARRAY[Webhook]',
        };
}
# @return ARRAY[Webhook]
#
sub webhook_get {
    my ($self, %args) = @_;

    # parse inputs
    my $_resource_path = '/webhook';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # query params
    if ( exists $args{'limit'}) {
        $query_params->{'limit'} = $self->{api_client}->to_query_value($args{'limit'});
    }

    # query params
    if ( exists $args{'offset'}) {
        $query_params->{'offset'} = $self->{api_client}->to_query_value($args{'offset'});
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(apikey )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('ARRAY[Webhook]', $response);
    return $_response_object;
}

#
# webhook_post
#
# Add Webhook
#
# @param WebhookCreatePayload $webhook_create_payload  (required)
{
    my $params = {
    'webhook_create_payload' => {
        data_type => 'WebhookCreatePayload',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'webhook_post' } = {
        summary => 'Add Webhook',
        params => $params,
        returns => 'Webhook',
        };
}
# @return Webhook
#
sub webhook_post {
    my ($self, %args) = @_;

    # verify the required parameter 'webhook_create_payload' is set
    unless (exists $args{'webhook_create_payload'}) {
      croak("Missing the required parameter 'webhook_create_payload' when calling webhook_post");
    }

    # parse inputs
    my $_resource_path = '/webhook';

    my $_method = 'POST';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    my $_body_data;
    # body params
    if ( exists $args{'webhook_create_payload'}) {
        $_body_data = $args{'webhook_create_payload'};
    }

    # authentication setting, if any
    my $auth_settings = [qw(apikey )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('Webhook', $response);
    return $_response_object;
}

1;
