=begin comment

Elastic Email REST API

This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    The API has a limit of 20 concurrent connections and a hard timeout of 600 seconds per request.    To start using this API, you will need your Access Token (available <a target=\"_blank\" href=\"https://app.elasticemail.com/marketing/settings/new/manage-api\">here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    Downloadable library clients can be found in our Github repository <a target=\"_blank\" href=\"https://github.com/ElasticEmail?tab=repositories&q=%22rest+api%22+in%3Areadme\">here</a>

The version of the OpenAPI document: 4.0.0
Contact: support@elasticemail.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More;
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('ElasticEmail::ContactsApi');

my $api = ElasticEmail::ContactsApi->new();
isa_ok($api, 'ElasticEmail::ContactsApi');

#
# contacts_by_email_delete test
#
# uncomment below and update the test
#my $contacts_by_email_delete_email = undef; # replace NULL with a proper value
#my $contacts_by_email_delete_result = $api->contacts_by_email_delete(email => $contacts_by_email_delete_email);

#
# contacts_by_email_get test
#
# uncomment below and update the test
#my $contacts_by_email_get_email = undef; # replace NULL with a proper value
#my $contacts_by_email_get_result = $api->contacts_by_email_get(email => $contacts_by_email_get_email);

#
# contacts_by_email_put test
#
# uncomment below and update the test
#my $contacts_by_email_put_email = undef; # replace NULL with a proper value
#my $contacts_by_email_put_contact_update_payload = undef; # replace NULL with a proper value
#my $contacts_by_email_put_result = $api->contacts_by_email_put(email => $contacts_by_email_put_email, contact_update_payload => $contacts_by_email_put_contact_update_payload);

#
# contacts_delete_post test
#
# uncomment below and update the test
#my $contacts_delete_post_emails_payload = undef; # replace NULL with a proper value
#my $contacts_delete_post_result = $api->contacts_delete_post(emails_payload => $contacts_delete_post_emails_payload);

#
# contacts_export_by_id_status_get test
#
# uncomment below and update the test
#my $contacts_export_by_id_status_get_id = undef; # replace NULL with a proper value
#my $contacts_export_by_id_status_get_result = $api->contacts_export_by_id_status_get(id => $contacts_export_by_id_status_get_id);

#
# contacts_export_post test
#
# uncomment below and update the test
#my $contacts_export_post_file_format = undef; # replace NULL with a proper value
#my $contacts_export_post_rule = undef; # replace NULL with a proper value
#my $contacts_export_post_emails = undef; # replace NULL with a proper value
#my $contacts_export_post_compression_format = undef; # replace NULL with a proper value
#my $contacts_export_post_file_name = undef; # replace NULL with a proper value
#my $contacts_export_post_result = $api->contacts_export_post(file_format => $contacts_export_post_file_format, rule => $contacts_export_post_rule, emails => $contacts_export_post_emails, compression_format => $contacts_export_post_compression_format, file_name => $contacts_export_post_file_name);

#
# contacts_get test
#
# uncomment below and update the test
#my $contacts_get_limit = undef; # replace NULL with a proper value
#my $contacts_get_offset = undef; # replace NULL with a proper value
#my $contacts_get_result = $api->contacts_get(limit => $contacts_get_limit, offset => $contacts_get_offset);

#
# contacts_import_post test
#
# uncomment below and update the test
#my $contacts_import_post_list_name = undef; # replace NULL with a proper value
#my $contacts_import_post_encoding_name = undef; # replace NULL with a proper value
#my $contacts_import_post_file_url = undef; # replace NULL with a proper value
#my $contacts_import_post_file = undef; # replace NULL with a proper value
#my $contacts_import_post_result = $api->contacts_import_post(list_name => $contacts_import_post_list_name, encoding_name => $contacts_import_post_encoding_name, file_url => $contacts_import_post_file_url, file => $contacts_import_post_file);

#
# contacts_post test
#
# uncomment below and update the test
#my $contacts_post_contact_payload = undef; # replace NULL with a proper value
#my $contacts_post_listnames = undef; # replace NULL with a proper value
#my $contacts_post_result = $api->contacts_post(contact_payload => $contacts_post_contact_payload, listnames => $contacts_post_listnames);


done_testing();
