=begin comment

Elastic Email REST API

This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    The API has a limit of 20 concurrent connections and a hard timeout of 600 seconds per request.    To start using this API, you will need your Access Token (available <a target=\"_blank\" href=\"https://app.elasticemail.com/marketing/settings/new/manage-api\">here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    Downloadable library clients can be found in our Github repository <a target=\"_blank\" href=\"https://github.com/ElasticEmail?tab=repositories&q=%22rest+api%22+in%3Areadme\">here</a>

The version of the OpenAPI document: 4.0.0
Contact: support@elasticemail.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More;
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('ElasticEmail::DomainsApi');

my $api = ElasticEmail::DomainsApi->new();
isa_ok($api, 'ElasticEmail::DomainsApi');

#
# domains_by_domain_delete test
#
# uncomment below and update the test
#my $domains_by_domain_delete_domain = undef; # replace NULL with a proper value
#my $domains_by_domain_delete_result = $api->domains_by_domain_delete(domain => $domains_by_domain_delete_domain);

#
# domains_by_domain_get test
#
# uncomment below and update the test
#my $domains_by_domain_get_domain = undef; # replace NULL with a proper value
#my $domains_by_domain_get_result = $api->domains_by_domain_get(domain => $domains_by_domain_get_domain);

#
# domains_by_domain_put test
#
# uncomment below and update the test
#my $domains_by_domain_put_domain = undef; # replace NULL with a proper value
#my $domains_by_domain_put_domain_update_payload = undef; # replace NULL with a proper value
#my $domains_by_domain_put_result = $api->domains_by_domain_put(domain => $domains_by_domain_put_domain, domain_update_payload => $domains_by_domain_put_domain_update_payload);

#
# domains_by_domain_restricted_get test
#
# uncomment below and update the test
#my $domains_by_domain_restricted_get_domain = undef; # replace NULL with a proper value
#my $domains_by_domain_restricted_get_result = $api->domains_by_domain_restricted_get(domain => $domains_by_domain_restricted_get_domain);

#
# domains_by_domain_verification_put test
#
# uncomment below and update the test
#my $domains_by_domain_verification_put_domain = undef; # replace NULL with a proper value
#my $domains_by_domain_verification_put_body = undef; # replace NULL with a proper value
#my $domains_by_domain_verification_put_result = $api->domains_by_domain_verification_put(domain => $domains_by_domain_verification_put_domain, body => $domains_by_domain_verification_put_body);

#
# domains_by_email_default_patch test
#
# uncomment below and update the test
#my $domains_by_email_default_patch_email = undef; # replace NULL with a proper value
#my $domains_by_email_default_patch_result = $api->domains_by_email_default_patch(email => $domains_by_email_default_patch_email);

#
# domains_get test
#
# uncomment below and update the test
#my $domains_get_result = $api->domains_get();

#
# domains_post test
#
# uncomment below and update the test
#my $domains_post_domain_payload = undef; # replace NULL with a proper value
#my $domains_post_result = $api->domains_post(domain_payload => $domains_post_domain_payload);


done_testing();
