=begin comment

Elastic Email REST API

This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    The API has a limit of 20 concurrent connections and a hard timeout of 600 seconds per request.    To start using this API, you will need your Access Token (available <a target=\"_blank\" href=\"https://app.elasticemail.com/marketing/settings/new/manage-api\">here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    Downloadable library clients can be found in our Github repository <a target=\"_blank\" href=\"https://github.com/ElasticEmail?tab=repositories&q=%22rest+api%22+in%3Areadme\">here</a>

The version of the OpenAPI document: 4.0.0
Contact: support@elasticemail.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More;
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('ElasticEmail::EmailsApi');

my $api = ElasticEmail::EmailsApi->new();
isa_ok($api, 'ElasticEmail::EmailsApi');

#
# emails_by_msgid_view_get test
#
# uncomment below and update the test
#my $emails_by_msgid_view_get_msgid = undef; # replace NULL with a proper value
#my $emails_by_msgid_view_get_result = $api->emails_by_msgid_view_get(msgid => $emails_by_msgid_view_get_msgid);

#
# emails_by_transactionid_status_get test
#
# uncomment below and update the test
#my $emails_by_transactionid_status_get_transactionid = undef; # replace NULL with a proper value
#my $emails_by_transactionid_status_get_show_failed = undef; # replace NULL with a proper value
#my $emails_by_transactionid_status_get_show_sent = undef; # replace NULL with a proper value
#my $emails_by_transactionid_status_get_show_delivered = undef; # replace NULL with a proper value
#my $emails_by_transactionid_status_get_show_pending = undef; # replace NULL with a proper value
#my $emails_by_transactionid_status_get_show_opened = undef; # replace NULL with a proper value
#my $emails_by_transactionid_status_get_show_clicked = undef; # replace NULL with a proper value
#my $emails_by_transactionid_status_get_show_abuse = undef; # replace NULL with a proper value
#my $emails_by_transactionid_status_get_show_unsubscribed = undef; # replace NULL with a proper value
#my $emails_by_transactionid_status_get_show_errors = undef; # replace NULL with a proper value
#my $emails_by_transactionid_status_get_show_message_ids = undef; # replace NULL with a proper value
#my $emails_by_transactionid_status_get_result = $api->emails_by_transactionid_status_get(transactionid => $emails_by_transactionid_status_get_transactionid, show_failed => $emails_by_transactionid_status_get_show_failed, show_sent => $emails_by_transactionid_status_get_show_sent, show_delivered => $emails_by_transactionid_status_get_show_delivered, show_pending => $emails_by_transactionid_status_get_show_pending, show_opened => $emails_by_transactionid_status_get_show_opened, show_clicked => $emails_by_transactionid_status_get_show_clicked, show_abuse => $emails_by_transactionid_status_get_show_abuse, show_unsubscribed => $emails_by_transactionid_status_get_show_unsubscribed, show_errors => $emails_by_transactionid_status_get_show_errors, show_message_ids => $emails_by_transactionid_status_get_show_message_ids);

#
# emails_mergefile_post test
#
# uncomment below and update the test
#my $emails_mergefile_post_merge_email_payload = undef; # replace NULL with a proper value
#my $emails_mergefile_post_result = $api->emails_mergefile_post(merge_email_payload => $emails_mergefile_post_merge_email_payload);

#
# emails_post test
#
# uncomment below and update the test
#my $emails_post_email_message_data = undef; # replace NULL with a proper value
#my $emails_post_result = $api->emails_post(email_message_data => $emails_post_email_message_data);

#
# emails_transactional_post test
#
# uncomment below and update the test
#my $emails_transactional_post_email_transactional_message_data = undef; # replace NULL with a proper value
#my $emails_transactional_post_result = $api->emails_transactional_post(email_transactional_message_data => $emails_transactional_post_email_transactional_message_data);


done_testing();
