=begin comment

Elastic Email REST API

This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    To start using this API, you will need your Access Token (available <a href=\"https://elasticemail.com/account#/settings/new/manage-api\">here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    This is the documentation for REST API. If you’d like to read our legacy documentation regarding Web API v2 click <a href=\"https://api.elasticemail.com/public/help\">here</a>.

The version of the OpenAPI document: 4.0.0
Contact: support@elasticemail.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('ElasticEmail::EventsApi');

my $api = ElasticEmail::EventsApi->new();
isa_ok($api, 'ElasticEmail::EventsApi');

#
# events_by_transactionid_get test
#
{
    my $transactionid = undef; # replace NULL with a proper value
    my $from = undef; # replace NULL with a proper value
    my $to = undef; # replace NULL with a proper value
    my $order_by = undef; # replace NULL with a proper value
    my $limit = undef; # replace NULL with a proper value
    my $offset = undef; # replace NULL with a proper value
    my $result = $api->events_by_transactionid_get(transactionid => $transactionid, from => $from, to => $to, order_by => $order_by, limit => $limit, offset => $offset);
}

#
# events_channels_by_name_export_post test
#
{
    my $name = undef; # replace NULL with a proper value
    my $event_types = undef; # replace NULL with a proper value
    my $from = undef; # replace NULL with a proper value
    my $to = undef; # replace NULL with a proper value
    my $file_format = undef; # replace NULL with a proper value
    my $compression_format = undef; # replace NULL with a proper value
    my $file_name = undef; # replace NULL with a proper value
    my $result = $api->events_channels_by_name_export_post(name => $name, event_types => $event_types, from => $from, to => $to, file_format => $file_format, compression_format => $compression_format, file_name => $file_name);
}

#
# events_channels_by_name_get test
#
{
    my $name = undef; # replace NULL with a proper value
    my $event_types = undef; # replace NULL with a proper value
    my $from = undef; # replace NULL with a proper value
    my $to = undef; # replace NULL with a proper value
    my $order_by = undef; # replace NULL with a proper value
    my $limit = undef; # replace NULL with a proper value
    my $offset = undef; # replace NULL with a proper value
    my $result = $api->events_channels_by_name_get(name => $name, event_types => $event_types, from => $from, to => $to, order_by => $order_by, limit => $limit, offset => $offset);
}

#
# events_channels_export_by_id_status_get test
#
{
    my $id = undef; # replace NULL with a proper value
    my $result = $api->events_channels_export_by_id_status_get(id => $id);
}

#
# events_export_by_id_status_get test
#
{
    my $id = undef; # replace NULL with a proper value
    my $result = $api->events_export_by_id_status_get(id => $id);
}

#
# events_export_post test
#
{
    my $event_types = undef; # replace NULL with a proper value
    my $from = undef; # replace NULL with a proper value
    my $to = undef; # replace NULL with a proper value
    my $file_format = undef; # replace NULL with a proper value
    my $compression_format = undef; # replace NULL with a proper value
    my $file_name = undef; # replace NULL with a proper value
    my $result = $api->events_export_post(event_types => $event_types, from => $from, to => $to, file_format => $file_format, compression_format => $compression_format, file_name => $file_name);
}

#
# events_get test
#
{
    my $event_types = undef; # replace NULL with a proper value
    my $from = undef; # replace NULL with a proper value
    my $to = undef; # replace NULL with a proper value
    my $order_by = undef; # replace NULL with a proper value
    my $limit = undef; # replace NULL with a proper value
    my $offset = undef; # replace NULL with a proper value
    my $result = $api->events_get(event_types => $event_types, from => $from, to => $to, order_by => $order_by, limit => $limit, offset => $offset);
}


1;
