=begin comment

Elastic Email REST API

This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    To start using this API, you will need your Access Token (available <a href=\"https://elasticemail.com/account#/settings/new/manage-api\">here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    This is the documentation for REST API. If you’d like to read our legacy documentation regarding Web API v2 click <a href=\"https://api.elasticemail.com/public/help\">here</a>.

The version of the OpenAPI document: 4.0.0
Contact: support@elasticemail.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('ElasticEmail::InboundRouteApi');

my $api = ElasticEmail::InboundRouteApi->new();
isa_ok($api, 'ElasticEmail::InboundRouteApi');

#
# inboundroute_by_id_delete test
#
{
    my $id = undef; # replace NULL with a proper value
    my $result = $api->inboundroute_by_id_delete(id => $id);
}

#
# inboundroute_by_id_get test
#
{
    my $id = undef; # replace NULL with a proper value
    my $result = $api->inboundroute_by_id_get(id => $id);
}

#
# inboundroute_by_id_put test
#
{
    my $id = undef; # replace NULL with a proper value
    my $inbound_payload = undef; # replace NULL with a proper value
    my $result = $api->inboundroute_by_id_put(id => $id, inbound_payload => $inbound_payload);
}

#
# inboundroute_get test
#
{
    my $result = $api->inboundroute_get();
}

#
# inboundroute_order_put test
#
{
    my $sort_order_item = undef; # replace NULL with a proper value
    my $result = $api->inboundroute_order_put(sort_order_item => $sort_order_item);
}

#
# inboundroute_post test
#
{
    my $inbound_payload = undef; # replace NULL with a proper value
    my $result = $api->inboundroute_post(inbound_payload => $inbound_payload);
}


1;
