=begin comment

Elastic Email REST API

This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    The API has a limit of 20 concurrent connections and a hard timeout of 600 seconds per request.    To start using this API, you will need your Access Token (available <a target=\"_blank\" href=\"https://app.elasticemail.com/marketing/settings/new/manage-api\">here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    Downloadable library clients can be found in our Github repository <a target=\"_blank\" href=\"https://github.com/ElasticEmail?tab=repositories&q=%22rest+api%22+in%3Areadme\">here</a>

The version of the OpenAPI document: 4.0.0
Contact: support@elasticemail.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More;
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('ElasticEmail::ListsApi');

my $api = ElasticEmail::ListsApi->new();
isa_ok($api, 'ElasticEmail::ListsApi');

#
# lists_by_listname_contacts_get test
#
# uncomment below and update the test
#my $lists_by_listname_contacts_get_listname = undef; # replace NULL with a proper value
#my $lists_by_listname_contacts_get_limit = undef; # replace NULL with a proper value
#my $lists_by_listname_contacts_get_offset = undef; # replace NULL with a proper value
#my $lists_by_listname_contacts_get_result = $api->lists_by_listname_contacts_get(listname => $lists_by_listname_contacts_get_listname, limit => $lists_by_listname_contacts_get_limit, offset => $lists_by_listname_contacts_get_offset);

#
# lists_by_name_contacts_post test
#
# uncomment below and update the test
#my $lists_by_name_contacts_post_name = undef; # replace NULL with a proper value
#my $lists_by_name_contacts_post_emails_payload = undef; # replace NULL with a proper value
#my $lists_by_name_contacts_post_result = $api->lists_by_name_contacts_post(name => $lists_by_name_contacts_post_name, emails_payload => $lists_by_name_contacts_post_emails_payload);

#
# lists_by_name_contacts_remove_post test
#
# uncomment below and update the test
#my $lists_by_name_contacts_remove_post_name = undef; # replace NULL with a proper value
#my $lists_by_name_contacts_remove_post_emails_payload = undef; # replace NULL with a proper value
#my $lists_by_name_contacts_remove_post_result = $api->lists_by_name_contacts_remove_post(name => $lists_by_name_contacts_remove_post_name, emails_payload => $lists_by_name_contacts_remove_post_emails_payload);

#
# lists_by_name_delete test
#
# uncomment below and update the test
#my $lists_by_name_delete_name = undef; # replace NULL with a proper value
#my $lists_by_name_delete_result = $api->lists_by_name_delete(name => $lists_by_name_delete_name);

#
# lists_by_name_get test
#
# uncomment below and update the test
#my $lists_by_name_get_name = undef; # replace NULL with a proper value
#my $lists_by_name_get_result = $api->lists_by_name_get(name => $lists_by_name_get_name);

#
# lists_by_name_put test
#
# uncomment below and update the test
#my $lists_by_name_put_name = undef; # replace NULL with a proper value
#my $lists_by_name_put_list_update_payload = undef; # replace NULL with a proper value
#my $lists_by_name_put_result = $api->lists_by_name_put(name => $lists_by_name_put_name, list_update_payload => $lists_by_name_put_list_update_payload);

#
# lists_get test
#
# uncomment below and update the test
#my $lists_get_limit = undef; # replace NULL with a proper value
#my $lists_get_offset = undef; # replace NULL with a proper value
#my $lists_get_result = $api->lists_get(limit => $lists_get_limit, offset => $lists_get_offset);

#
# lists_post test
#
# uncomment below and update the test
#my $lists_post_list_payload = undef; # replace NULL with a proper value
#my $lists_post_result = $api->lists_post(list_payload => $lists_post_list_payload);


done_testing();
