=begin comment

Elastic Email REST API

This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    The API has a limit of 20 concurrent connections and a hard timeout of 600 seconds per request.    To start using this API, you will need your Access Token (available <a target=\"_blank\" href=\"https://app.elasticemail.com/marketing/settings/new/manage-api\">here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    Downloadable library clients can be found in our Github repository <a target=\"_blank\" href=\"https://github.com/ElasticEmail?tab=repositories&q=%22rest+api%22+in%3Areadme\">here</a>

The version of the OpenAPI document: 4.0.0
Contact: support@elasticemail.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More;
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('ElasticEmail::SecurityApi');

my $api = ElasticEmail::SecurityApi->new();
isa_ok($api, 'ElasticEmail::SecurityApi');

#
# security_apikeys_by_name_delete test
#
# uncomment below and update the test
#my $security_apikeys_by_name_delete_name = undef; # replace NULL with a proper value
#my $security_apikeys_by_name_delete_subaccount = undef; # replace NULL with a proper value
#my $security_apikeys_by_name_delete_result = $api->security_apikeys_by_name_delete(name => $security_apikeys_by_name_delete_name, subaccount => $security_apikeys_by_name_delete_subaccount);

#
# security_apikeys_by_name_get test
#
# uncomment below and update the test
#my $security_apikeys_by_name_get_name = undef; # replace NULL with a proper value
#my $security_apikeys_by_name_get_subaccount = undef; # replace NULL with a proper value
#my $security_apikeys_by_name_get_result = $api->security_apikeys_by_name_get(name => $security_apikeys_by_name_get_name, subaccount => $security_apikeys_by_name_get_subaccount);

#
# security_apikeys_by_name_put test
#
# uncomment below and update the test
#my $security_apikeys_by_name_put_name = undef; # replace NULL with a proper value
#my $security_apikeys_by_name_put_api_key_payload = undef; # replace NULL with a proper value
#my $security_apikeys_by_name_put_result = $api->security_apikeys_by_name_put(name => $security_apikeys_by_name_put_name, api_key_payload => $security_apikeys_by_name_put_api_key_payload);

#
# security_apikeys_get test
#
# uncomment below and update the test
#my $security_apikeys_get_subaccount = undef; # replace NULL with a proper value
#my $security_apikeys_get_result = $api->security_apikeys_get(subaccount => $security_apikeys_get_subaccount);

#
# security_apikeys_post test
#
# uncomment below and update the test
#my $security_apikeys_post_api_key_payload = undef; # replace NULL with a proper value
#my $security_apikeys_post_result = $api->security_apikeys_post(api_key_payload => $security_apikeys_post_api_key_payload);

#
# security_smtp_by_name_delete test
#
# uncomment below and update the test
#my $security_smtp_by_name_delete_name = undef; # replace NULL with a proper value
#my $security_smtp_by_name_delete_subaccount = undef; # replace NULL with a proper value
#my $security_smtp_by_name_delete_result = $api->security_smtp_by_name_delete(name => $security_smtp_by_name_delete_name, subaccount => $security_smtp_by_name_delete_subaccount);

#
# security_smtp_by_name_get test
#
# uncomment below and update the test
#my $security_smtp_by_name_get_name = undef; # replace NULL with a proper value
#my $security_smtp_by_name_get_subaccount = undef; # replace NULL with a proper value
#my $security_smtp_by_name_get_result = $api->security_smtp_by_name_get(name => $security_smtp_by_name_get_name, subaccount => $security_smtp_by_name_get_subaccount);

#
# security_smtp_by_name_put test
#
# uncomment below and update the test
#my $security_smtp_by_name_put_name = undef; # replace NULL with a proper value
#my $security_smtp_by_name_put_smtp_credentials_payload = undef; # replace NULL with a proper value
#my $security_smtp_by_name_put_result = $api->security_smtp_by_name_put(name => $security_smtp_by_name_put_name, smtp_credentials_payload => $security_smtp_by_name_put_smtp_credentials_payload);

#
# security_smtp_get test
#
# uncomment below and update the test
#my $security_smtp_get_subaccount = undef; # replace NULL with a proper value
#my $security_smtp_get_result = $api->security_smtp_get(subaccount => $security_smtp_get_subaccount);

#
# security_smtp_post test
#
# uncomment below and update the test
#my $security_smtp_post_smtp_credentials_payload = undef; # replace NULL with a proper value
#my $security_smtp_post_result = $api->security_smtp_post(smtp_credentials_payload => $security_smtp_post_smtp_credentials_payload);


done_testing();
