=begin comment

Elastic Email REST API

This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    To start using this API, you will need your Access Token (available <a href=\"https://elasticemail.com/account#/settings/new/manage-api\">here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    This is the documentation for REST API. If you’d like to read our legacy documentation regarding Web API v2 click <a href=\"https://api.elasticemail.com/public/help\">here</a>.

The version of the OpenAPI document: 4.0.0
Contact: support@elasticemail.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('ElasticEmail::SecurityApi');

my $api = ElasticEmail::SecurityApi->new();
isa_ok($api, 'ElasticEmail::SecurityApi');

#
# security_apikeys_by_name_delete test
#
{
    my $name = undef; # replace NULL with a proper value
    my $subaccount = undef; # replace NULL with a proper value
    my $result = $api->security_apikeys_by_name_delete(name => $name, subaccount => $subaccount);
}

#
# security_apikeys_by_name_get test
#
{
    my $name = undef; # replace NULL with a proper value
    my $subaccount = undef; # replace NULL with a proper value
    my $result = $api->security_apikeys_by_name_get(name => $name, subaccount => $subaccount);
}

#
# security_apikeys_by_name_put test
#
{
    my $name = undef; # replace NULL with a proper value
    my $api_key_payload = undef; # replace NULL with a proper value
    my $result = $api->security_apikeys_by_name_put(name => $name, api_key_payload => $api_key_payload);
}

#
# security_apikeys_get test
#
{
    my $subaccount = undef; # replace NULL with a proper value
    my $result = $api->security_apikeys_get(subaccount => $subaccount);
}

#
# security_apikeys_post test
#
{
    my $api_key_payload = undef; # replace NULL with a proper value
    my $result = $api->security_apikeys_post(api_key_payload => $api_key_payload);
}

#
# security_smtp_by_name_delete test
#
{
    my $name = undef; # replace NULL with a proper value
    my $subaccount = undef; # replace NULL with a proper value
    my $result = $api->security_smtp_by_name_delete(name => $name, subaccount => $subaccount);
}

#
# security_smtp_by_name_get test
#
{
    my $name = undef; # replace NULL with a proper value
    my $subaccount = undef; # replace NULL with a proper value
    my $result = $api->security_smtp_by_name_get(name => $name, subaccount => $subaccount);
}

#
# security_smtp_by_name_put test
#
{
    my $name = undef; # replace NULL with a proper value
    my $smtp_credentials_payload = undef; # replace NULL with a proper value
    my $result = $api->security_smtp_by_name_put(name => $name, smtp_credentials_payload => $smtp_credentials_payload);
}

#
# security_smtp_get test
#
{
    my $subaccount = undef; # replace NULL with a proper value
    my $result = $api->security_smtp_get(subaccount => $subaccount);
}

#
# security_smtp_post test
#
{
    my $smtp_credentials_payload = undef; # replace NULL with a proper value
    my $result = $api->security_smtp_post(smtp_credentials_payload => $smtp_credentials_payload);
}


1;
