=begin comment

Elastic Email REST API

This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    To start using this API, you will need your Access Token (available <a href=\"https://elasticemail.com/account#/settings/new/manage-api\">here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    This is the documentation for REST API. If you’d like to read our legacy documentation regarding Web API v2 click <a href=\"https://api.elasticemail.com/public/help\">here</a>.

The version of the OpenAPI document: 4.0.0
Contact: support@elasticemail.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('ElasticEmail::SuppressionsApi');

my $api = ElasticEmail::SuppressionsApi->new();
isa_ok($api, 'ElasticEmail::SuppressionsApi');

#
# suppressions_bounces_get test
#
{
    my $search = undef; # replace NULL with a proper value
    my $limit = undef; # replace NULL with a proper value
    my $offset = undef; # replace NULL with a proper value
    my $result = $api->suppressions_bounces_get(search => $search, limit => $limit, offset => $offset);
}

#
# suppressions_bounces_import_post test
#
{
    my $file = undef; # replace NULL with a proper value
    my $result = $api->suppressions_bounces_import_post(file => $file);
}

#
# suppressions_bounces_post test
#
{
    my $request_body = undef; # replace NULL with a proper value
    my $result = $api->suppressions_bounces_post(request_body => $request_body);
}

#
# suppressions_by_email_delete test
#
{
    my $email = undef; # replace NULL with a proper value
    my $result = $api->suppressions_by_email_delete(email => $email);
}

#
# suppressions_by_email_get test
#
{
    my $email = undef; # replace NULL with a proper value
    my $result = $api->suppressions_by_email_get(email => $email);
}

#
# suppressions_complaints_get test
#
{
    my $search = undef; # replace NULL with a proper value
    my $limit = undef; # replace NULL with a proper value
    my $offset = undef; # replace NULL with a proper value
    my $result = $api->suppressions_complaints_get(search => $search, limit => $limit, offset => $offset);
}

#
# suppressions_complaints_import_post test
#
{
    my $file = undef; # replace NULL with a proper value
    my $result = $api->suppressions_complaints_import_post(file => $file);
}

#
# suppressions_complaints_post test
#
{
    my $request_body = undef; # replace NULL with a proper value
    my $result = $api->suppressions_complaints_post(request_body => $request_body);
}

#
# suppressions_get test
#
{
    my $limit = undef; # replace NULL with a proper value
    my $offset = undef; # replace NULL with a proper value
    my $result = $api->suppressions_get(limit => $limit, offset => $offset);
}

#
# suppressions_unsubscribes_get test
#
{
    my $search = undef; # replace NULL with a proper value
    my $limit = undef; # replace NULL with a proper value
    my $offset = undef; # replace NULL with a proper value
    my $result = $api->suppressions_unsubscribes_get(search => $search, limit => $limit, offset => $offset);
}

#
# suppressions_unsubscribes_import_post test
#
{
    my $file = undef; # replace NULL with a proper value
    my $result = $api->suppressions_unsubscribes_import_post(file => $file);
}

#
# suppressions_unsubscribes_post test
#
{
    my $request_body = undef; # replace NULL with a proper value
    my $result = $api->suppressions_unsubscribes_post(request_body => $request_body);
}


1;
