=begin comment

Elastic Email REST API

This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    The API has a limit of 20 concurrent connections and a hard timeout of 600 seconds per request.    To start using this API, you will need your Access Token (available <a target=\"_blank\" href=\"https://app.elasticemail.com/marketing/settings/new/manage-api\">here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    Downloadable library clients can be found in our Github repository <a target=\"_blank\" href=\"https://github.com/ElasticEmail?tab=repositories&q=%22rest+api%22+in%3Areadme\">here</a>

The version of the OpenAPI document: 4.0.0
Contact: support@elasticemail.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More;
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('ElasticEmail::VerificationsApi');

my $api = ElasticEmail::VerificationsApi->new();
isa_ok($api, 'ElasticEmail::VerificationsApi');

#
# verifications_by_email_delete test
#
# uncomment below and update the test
#my $verifications_by_email_delete_email = undef; # replace NULL with a proper value
#my $verifications_by_email_delete_result = $api->verifications_by_email_delete(email => $verifications_by_email_delete_email);

#
# verifications_by_email_get test
#
# uncomment below and update the test
#my $verifications_by_email_get_email = undef; # replace NULL with a proper value
#my $verifications_by_email_get_result = $api->verifications_by_email_get(email => $verifications_by_email_get_email);

#
# verifications_by_email_post test
#
# uncomment below and update the test
#my $verifications_by_email_post_email = undef; # replace NULL with a proper value
#my $verifications_by_email_post_result = $api->verifications_by_email_post(email => $verifications_by_email_post_email);

#
# verifications_files_by_id_delete test
#
# uncomment below and update the test
#my $verifications_files_by_id_delete_id = undef; # replace NULL with a proper value
#my $verifications_files_by_id_delete_result = $api->verifications_files_by_id_delete(id => $verifications_files_by_id_delete_id);

#
# verifications_files_by_id_result_download_get test
#
# uncomment below and update the test
#my $verifications_files_by_id_result_download_get_id = undef; # replace NULL with a proper value
#my $verifications_files_by_id_result_download_get_result = $api->verifications_files_by_id_result_download_get(id => $verifications_files_by_id_result_download_get_id);

#
# verifications_files_by_id_result_get test
#
# uncomment below and update the test
#my $verifications_files_by_id_result_get_id = undef; # replace NULL with a proper value
#my $verifications_files_by_id_result_get_limit = undef; # replace NULL with a proper value
#my $verifications_files_by_id_result_get_offset = undef; # replace NULL with a proper value
#my $verifications_files_by_id_result_get_result = $api->verifications_files_by_id_result_get(id => $verifications_files_by_id_result_get_id, limit => $verifications_files_by_id_result_get_limit, offset => $verifications_files_by_id_result_get_offset);

#
# verifications_files_by_id_verification_post test
#
# uncomment below and update the test
#my $verifications_files_by_id_verification_post_id = undef; # replace NULL with a proper value
#my $verifications_files_by_id_verification_post_result = $api->verifications_files_by_id_verification_post(id => $verifications_files_by_id_verification_post_id);

#
# verifications_files_post test
#
# uncomment below and update the test
#my $verifications_files_post_file = undef; # replace NULL with a proper value
#my $verifications_files_post_result = $api->verifications_files_post(file => $verifications_files_post_file);

#
# verifications_files_result_get test
#
# uncomment below and update the test
#my $verifications_files_result_get_result = $api->verifications_files_result_get();

#
# verifications_get test
#
# uncomment below and update the test
#my $verifications_get_limit = undef; # replace NULL with a proper value
#my $verifications_get_offset = undef; # replace NULL with a proper value
#my $verifications_get_result = $api->verifications_get(limit => $verifications_get_limit, offset => $verifications_get_offset);


done_testing();
