=begin comment

Elastic Email REST API

This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    The API has a limit of 20 concurrent connections and a hard timeout of 600 seconds per request.    To start using this API, you will need your Access Token (available <a target='_blank' href='https://app.elasticemail.com/marketing/settings/new/manage-api'>here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    Downloadable library clients can be found in our Github repository <a target='_blank' href='https://github.com/ElasticEmail?tab=repositories&q=%22rest+api%22+in%3Areadme'>here</a>

The version of the OpenAPI document: 4.0.0
Contact: support@elasticemail.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More;
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('ElasticEmail::WebhookApi');

my $api = ElasticEmail::WebhookApi->new();
isa_ok($api, 'ElasticEmail::WebhookApi');

#
# webhook_by_publicid_delete test
#
# uncomment below and update the test
#my $webhook_by_publicid_delete_publicid = undef; # replace NULL with a proper value
#my $webhook_by_publicid_delete_result = $api->webhook_by_publicid_delete(publicid => $webhook_by_publicid_delete_publicid);

#
# webhook_by_publicid_get test
#
# uncomment below and update the test
#my $webhook_by_publicid_get_publicid = undef; # replace NULL with a proper value
#my $webhook_by_publicid_get_result = $api->webhook_by_publicid_get(publicid => $webhook_by_publicid_get_publicid);

#
# webhook_by_publicid_put test
#
# uncomment below and update the test
#my $webhook_by_publicid_put_publicid = undef; # replace NULL with a proper value
#my $webhook_by_publicid_put_webhook_update_payload = undef; # replace NULL with a proper value
#my $webhook_by_publicid_put_result = $api->webhook_by_publicid_put(publicid => $webhook_by_publicid_put_publicid, webhook_update_payload => $webhook_by_publicid_put_webhook_update_payload);

#
# webhook_get test
#
# uncomment below and update the test
#my $webhook_get_limit = undef; # replace NULL with a proper value
#my $webhook_get_offset = undef; # replace NULL with a proper value
#my $webhook_get_result = $api->webhook_get(limit => $webhook_get_limit, offset => $webhook_get_offset);

#
# webhook_post test
#
# uncomment below and update the test
#my $webhook_post_webhook_create_payload = undef; # replace NULL with a proper value
#my $webhook_post_result = $api->webhook_post(webhook_create_payload => $webhook_post_webhook_create_payload);


done_testing();
